# These categories will be applied to all DAGs in the repo.
categories:
  - ETL/ELT
  - Data Processing
  - Machine Learning
  - Weights & Biases
  - MLops
  - Cosmos
  - dbt
  - astro sdk
  - astro buildkit
  - Snowflake
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/customer_analytics.py